# general
APP_NAME = "Text Editor"
APP_VERSION = "0.1.0"

# font styles
DEFAULT_FONT = ("Helvetica", 12)
SMALL_FONT = ("Helvetica", 10)

# backgrounds
BACKGROUND_COLOR = "#FFFFFF"
FOREGROUND_COLOR = "#000000"
SELECT_BACKGROUND = "#63A7FF"
BUTTON_BACKGROUND = "#D9D9D9"

# colors
LIGHT_GRAY = "#F0F0F0"
WHITE_COLOR = "#FFFFFF"
